### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#10]
###### Implementierung
Momentan mit `geocoder` gem. Einfachste Benutzung in Konsole (irb / pry / rails console): `Geocoder.search <address>`, gibt ein Array von Result-Objekten zurück, wo man jeweils mit `.data` die Daten abfragen kann

###### Todos / offene Fragen
- [x] Validierung falscher Adressen
- [x] Fehlermeldung bei nicht-existenter Adresse
- Reverse Geocoding
  - [x] Basis-Features (Button, Klick auf Karte, überträgt Features in Formular)
- [ ] POIs-Preview

**Comment by kjoscha** [comment]
@andneuma cool, dass der PR nun gemerged ist. Also, nun folgendermaßen weiter?
- Du baust die Fehlermeldungen ein
- Ich baue das Reverse-Geocoding (Klick auf Karte mit Redirect zum vorbefüllten Formular)

Hier Codeschnippsel aus einem anderen Projekt, die bei der Fehlermeldung weiterhelfen können (to be enhanced):

**Conroller:**
```
if @errors.any?
  render 'admin/error_alert.js'
```
**JS:**
 ```
var alert = "<div  style='position:fixed; z-index:9999;'' class='alert alert-warning'><%= @errors[0] %>TEST</div>";
jQuery('body').prepend(alert);
jQuery('.alert').fadeOut(5000, function() {$(this).remove()} );
```

**Comment by andneuma** [comment]
Machen wir so!

**Comment by andneuma** [comment]
> Ich baue das Reverse-Geocoding (Klick auf Karte mit Redirect zum vorbefüllten Formular)

"Take from current location" wäre cool (wie bei der alten Map)

**Comment by andneuma** [comment]
Mmmhh... Adresse überprüfen geht echt nur so mittelgut muss ich feststellen. Auch nominatim spuckt für _Magdalenenstraße 19435034, 10365, Berlin_ lat/lon aus :/ Muss dann wohl tatsächlich über preview oder einfach garnicht laufen...
