### ISSUE TITLE
Model versioning

### ISSUE THREAD

**Issue by andneuma** [magdalena19/lberg-map#95]
Puh, das wird ein ganz schönes Stück Arbeit. Ich schätze, da werden deine JS Künste auch nochmal gefragt sein, weil wir verschiedene Relationen versionieren und sich das alles im gleichen Frontend abspielen soll. Sollten wir face2face auch nochmal besprechen. Ich hab heut mal ein bisschen mit der Auditing-Gem rumgespielt, ist schon ganz cool wenn auch stellenweise undurchsichtig. Die Tage sollte dann der erste PR für die Basics kommen

**Comment by andneuma** [comment]
## Todos

* [ ] Move partials to subfolder ./places/review/
* [ ] Make review only available if unreviewed changes appear in object
* [ ] IP tracking (in case of Nazi spam)?
* [ ] Basic html diffing
* [ ] Revert to original state (i.e. delete all changes since last reviewed version after confirmation dialogue)
  * Keep one version before as backup?
* [ ] Accept selected changes
  * Translations via checkboxes

**Comment by magdalena19** [comment]
@andneuma hier gibt es doch ne umgangreiche Dokumentation: https://github.com/airblade/paper_trail

**Comment by andneuma** [comment]
## Gem-Dokumentationen

* PaperTrail: https://github.com/airblade/paper_trail
* Globalize-Versioning: https://github.com/globalize/globalize-versioning

## Anforderungen

### Features

* [ ] IP tracking (e.g. useful in case of Nazi spam)?
* [ ] Basic html diffing of unreviewed changes with reviewed version if exists
* [ ] Discard changes function (delete all changes since last reviewed version after confirmation dialogue)
* [ ] Accept checkbox selected changes (seperately) for...
  * place changes
  * categories changes
  * translation changes => individual selection of translations shall be possible!

### Views

* [ ] Make review only available if unreviewed changes appear in object

### To Test

#### POIs
- [ ] Wenn neuer POI durch **guest user** erstellt
  * `reviewed: false`
  * `versions.size == 1`
- [ ] Wenn neuer POI durch **authorisierte user** erstellt
  * `reviewed: true`
  * `versions.size == 1`
- [ ] Wenn bestehender POI durch **guest user** editiert
  * `reviewed: false`
  * `versions.size == n`
  * __mit n == 2 für simple Version__
- [ ] Wenn bestehender POI durch **authorisierte user** editiert
  * `reviewed: true`
  * `versions.size == n`
  * __mit n == 2 für simple Version__
 - [ ] Wenn POI durch **authorisierte user** gereviewed
  * `reviewed: true`
  * __lösche version history, sodass__ `versions.size == 1`

#### Translations

__on create__

- [ ] Für automatisch übersetzte Translations gilt...
  * `auto_translated: true`
  * `reviewed: false`
  * `versions.size == 1`
- [ ] Für nicht-automatisch übersetzte Translations durch **guest user** gilt...
  * `auto_translated: false`
  * `reviewed: false`
  * `versions.size == 1`
- [ ] Für nicht-automatisch übersetzte Translations durch **authorisierte user** gilt...
  * `auto_translated: false`
  * `reviewed: false`
  * `versions.size == 1`

  __on update__

  - [ ] Für alle automatisch übersetzte Translations gilt...
  * `auto_translated: true`
  * `reviewed: false`
  * `versions.size == 1`
  - [ ] Für nicht-automatisch übersetzte Translations durch **guest user** gilt...
  * `auto_translated: false`
  * `reviewed: false`
  * `versions.size == 1`
  - [ ] Für nicht-automatisch übersetzte Translations durch **authorisierte user** gilt...
  * `auto_translated: false`
  * `reviewed: false`
  * `versions.size == 1`
  
#### Categories

* Das gleiche im Prinzip für die Kategorien, das versioning feature für associated ressources ist experimentell: https://github.com/airblade/paper_trail#4b-associations

### WICHTIG:

* Es gibt `without_versioning` methode für save / update, funkioniert so:

  ```
  <object>.without_versioning do
    object.update_attributes( attr: "asd")
  end
  ```

**Comment by magdalena19** [comment]
Bug: Wenn POI geändert und vor dem confirm/reject zugehörige Translation geändert wird, wird eine zweite Version angelegt

To do: Admin-Änderungen müssen nicht confirmt werden

**Comment by magdalena19** [comment]
To do: IP-Tracking
